name: Database Pipeline

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches:
      - main
      - dev
    types:
      - opened

concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  test_docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository to Github Workspace
        uses: actions/checkout@v3

      - name: Image build
        shell: bash
        run: |
          docker build -f Dockerfile -t wander/postgres-db .

      - name: Build and run container
        shell: bash
        run: |
          docker run -d --name test-db wander/postgres-db
          echo "Waiting for init scripts to complete"
          sleep 5
          docker exec test-db pg_isready -d wander-db || { echo "::error unsuccessful container build with " && docker logs --tail 50 test-db && exit 1; }
