name: Microservice Pipeline

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      DBNAME:
        required: true
      DBPASS:
        required: true
      DBUSER:
        required: true
  pull_request:
    branches:
      - main
      - dev
    types:
      - opened
  push:

concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository to Github Workspace
        uses: actions/checkout@v3

      - name: Run Tests
        shell: bash
        run: |
          npm i
          NODE_ENV=dev npm run test

  code-scan:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository to Github Workspace
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript

      - name: Autobuild
        uses: github/codeql-action/autobuild@v2

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
